apiVersion: apps/v1
kind: Deployment
metadata:
  name: ripple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ripple
  template:
    metadata:
      labels:
        app: ripple
    spec:
      containers:
        - name: rippled
          image: rippled:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: admin
              containerPort: 5005
            - name: peer
              containerPort: 51235
          resources:
            limits:
              memory: 256Mi
              cpu: "0.5"

---
apiVersion: v1
kind: Service
metadata:
  name: ripple-service
spec:
  selector:
    app: ripple
  type: LoadBalancer
  ports:
    - name: http-port
      port: 80
      targetPort: 80
      protocol: TCP
    - name: admin-port
      port: 5005
      targetPort: 5005
      protocol: TCP
    - name: peer-port
      port: 51235
      targetPort: 51235
      protocol: TCP
